name: todo_app
description: A simple todo app for kubak.dev workflow improvements
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.2
  bloc_concurrency: ^0.2.0
  database_repository:
    path: packages/database_repository
  declarative_refresh_indicator: ^0.1.0
  easy_debounce: ^2.0.2+1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.0
  flutter_bloc: ^8.0.1
  flutter_sticky_header: ^0.6.0
  flutter_svg: ^1.0.1
  freezed_annotation: ^1.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  humanizer: ^1.0.0
  intl: ^0.17.0
  menu_button: ^1.4.2+1
  provider: ^6.0.2
  rubber:
    git:
      url: https://github.com/ArinFaraj/rubber.git
  rxdart: ^0.27.3
  scroll_to_index: ^2.1.1
  shared_preferences: ^2.0.12
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  vrouter: ^1.2.0+18

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  mocktail: ^0.2.0
  mocktail_image_network: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  #   - assets/rive/
  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo/Baloo.ttf
