name: database_repository
description: Dart package which manages the todo database api.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  chopper: ^4.0.1
  equatable: ^2.0.0
  hive: ^2.0.5
  json_annotation: ^4.1.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.12

dev_dependencies:
  build_runner: ^2.1.4
  chopper_generator: ^4.0.2
  json_serializable: ^5.0.0
  swagger_dart_code_generator: any
  very_good_analysis: ^2.4.0
